// chinese
let zh = {
  'edit': '编辑',
  'new': '新建',
  'search': '搜索',
  'deploy': '发布',
  'undo': '撤销',
  'redo': '重做',
  'cut': '剪切',
  'copy': '复制',
  'paste': '粘贴',
  'selectall': '全选',
  'about': '关于',
  'help': '使用帮助',
  'feedback': '提交问题',
  'settings': '配置',
  'view': '查看',
  'reload': '重新载入',
  'fullScreen': '切换全屏',
  'devTools': '切换开发者工具',
  'noArticleMsg': '无文章',
  'deleteArticleConfirmMsg': '是否确认删除该文章？',
  'successTitle': '成功',
  'deleteSuccessMsg': '删除成功',
  'selectHexoPath': '选择路径',
  'selectHexoPathTitle': '请先填写正确的Hexo安装目录',
  'okBtn': '确定',
  'menuArticle': '文章',
  'menuCreate': '发表',
  'menuSettings': '配置',
  'menuAbout': '关于',
  'searchPlaceholder': '想要查找什么...',
  'articleTitlePlaceholder': '文章标题',
  'articleContentPlaceholder': '开始编辑',
  'selectTags': '请选择标签',
  'selectCategories': '请选择分类',
  'save': '保存',
  'openToc': '开启目录',
  'settingTitlePath': 'Hexo路径',
  'settingTitleLanguage': '语言',
  'settingLanguagePlaceholder': '请选择语言',
  'chinese': '中文',
  'english': '英文',
  'settingTitleImageServer': '图片服务器',
  'settingImageServerPlaceholder': '请选择图片服务器'
}

// english
let en = {
  'edit': 'Edit',
  'new': 'New',
  'search': 'Search',
  'deploy': 'Deploy',
  'undo': 'Undo',
  'redo': 'Redo',
  'cut': 'Cut',
  'copy': 'Copy',
  'paste': 'Paste',
  'selectall': 'Select All',
  'about': 'About',
  'help': 'Help',
  'feedback': 'Submit Feedback',
  'settings': 'Settings',
  'view': 'View',
  'reload': 'Reload',
  'fullScreen': 'Toggle Full Screen',
  'devTools': 'Toggle DevTools',
  'noArticleMsg': 'Empty',
  'deleteArticleConfirmMsg': 'Are you sure to delete the article?',
  'successTitle': 'success',
  'deleteSuccessMsg': 'Delete success',
  'selectHexoPath': 'Path',
  'selectHexoPathTitle': 'Select hexo path',
  'okBtn': 'OK',
  'menuArticle': 'Article',
  'menuCreate': 'Create',
  'menuSettings': 'Settings',
  'menuAbout': 'About',
  'searchPlaceholder': 'keyword...',
  'articleTitlePlaceholder': 'Title...',
  'articleContentPlaceholder': 'Content...',
  'selectTags': 'Select tags',
  'selectCategories': 'Select categories',
  'save': 'Save',
  'openToc': 'TOC',
  'settingTitlePath': 'Hexo path',
  'settingTitleLanguage': 'Language',
  'settingLanguagePlaceholder': 'Select language',
  'chinese': 'Chinese',
  'english': 'English',
  'settingTitleImageServer': 'Image server',
  'settingImageServerPlaceholder': 'Select image server'
}

export default {
  en: {
    common: en
  },
  zh: {
    common: zh
  }
}
